### ISSUE TITLE
wrong character used for both LF and CRLF

### ISSUE THREAD

**Issue by benblo** [lancelot-coder-chen/line-ending-vsext#3]
I've used the extension on VS 2022 for years without issue, but I just installed it on a new Windows install (also VS 2022) and the characters render badly: LF looks like a pair of glasses, and CRLF looks like a mouse:
![image](https://github.com/user-attachments/assets/a67ac069-a33c-4699-acb7-bf6e562aa446)

I suppose this could be a font or encoding issue? any ideas how to fix it?

**Comment by robin88chen** [comment]
the extension use system font "Wingdings 3" to render the symbol. Maybe the font is different.
![1721783719955](https://github.com/user-attachments/assets/b56fdbd0-7c10-48fa-b09b-760af01b04e2)

**Comment by robin88chen** [comment]
Close after two weeks

**Comment by vitezslav-popovsky-solarwinds** [comment]
@benblo I had the same issue on "Windows Server 2022 Standard" where "Wingdings 3 Regular" font was missing. I copied  `WINGDNG3.TTF` from Windows 11 and installed it on my "Windows Server 2022 Standard" machine. That helped in my case.

![{F463CE22-2D8D-41E1-81CB-0054F10D12F6}](https://github.com/user-attachments/assets/7786021c-f783-4286-8d08-7d25326675d7)

**Comment by benblo** [comment]
That did the trick, thanks!
