### ISSUE TITLE
Line Endings should have `"Visible White Space"` color

### ISSUE THREAD

**Issue by vitezslav-popovsky-solarwinds** [lancelot-coder-chen/line-ending-vsext#5]
It's a bit confusing, that end-line marks have a `"Comment"` color:

https://github.com/robin88chen/line-ending-vsext/blob/19c5aa0f40558d7ab32c0fbe7a92868577612b42/LineEndings2022/LineEndingAdornment.cs#L131-L133

here is a print-screen of VS in a Dark Mode:

![{C0F85DEE-07E2-48AF-A284-07DA04EC9975}](https://github.com/user-attachments/assets/980c5c80-1e99-491a-a87c-7be692443850)

I believe it should be `"Visible White Space"` see [Fonts and Colors, Environment, Options dialog box - Visual Studio (Windows) | Microsoft Learn](https://learn.microsoft.com/en-us/visualstudio/ide/reference/fonts-and-colors-environment-options-dialog-box?view=vs-2022#see-also)

**Comment by vitezslav-popovsky-solarwinds** [comment]
I found a different extension, which uses `"Visible Whitespace"`

```csharp
var visibleWhitespace = formatMap.GetProperties("Visible Whitespace");
adornedTextView.AdornmentBrush = (Brush)visibleWhitespace[EditorFormatDefinition.ForegroundBrushId];
```

https://github.com/rolfwr/endoftheline/blob/b59e8c770ac3aac659a085fe4d172bafaa23b3b7/EndOfTheLine/EolAdornment.cs#L141-L142

**Comment by robin88chen** [comment]
line mark color has changed to visible whitespace color.
Thanks.
