### ISSUE TITLE
extension for Rider / IntelliJ?

### ISSUE THREAD

**Issue by benblo** [lancelot-coder-chen/line-ending-vsext#7]
Sorry this is a question not an issue, but does this extension (or a similar one) exist for Rider? (based on the IntelliJ family of IDEs, as I understand it)
I am transitioning from VS+R# to Rider, and got so used to your extension that it is now jarring for me to not clearing see the line ending characters :).

**Comment by robin88chen** [comment]
I'm sorry, I don't know. I never use Rider before.
